#!/usr/bin/env bash
# Script that sets up the web server - web-01
sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 777 /var/www

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
