#!/usr/bin/env bash
# Script that installs nginx in my webserver
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service restart nginx
