#!/usr/bin/env bash
# Configures my server

sudo apt-get update
sudo apt-get install nginx -y

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\	rewrite ^/redirect_me https://www.google.com  permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
